version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build-node:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build the Project
          command: npm run build
      - persist_to_workspace:  # This saves the build output for use in the deploy job
          root: .
          paths:
            - dist

  deploy:
    machine: true
    steps:
      - attach_workspace:  # This retrieves the build output saved in the build-node job
          at: ./dist
      - run:
          name: List dir
          command: ls
      - run:
          name: PWD
          command: pwd
      - run:
          name: Deploy to Server
          command: |
            scp -r ./dist/* spencer@184.171.221.186:/var/www/mrspinn
            ssh spencer@184.171.221.186 "sudo systemctl restart nginx"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-node:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build-node
          filters:
            branches:
              only: master
